### ISSUE TITLE
Do poprawy

### ISSUE THREAD

**Issue by kacgrzes** [mraq1234/submod8.3#1]
- [x] czy faktycznie potrzebujemy akcji `getCountries` ?
- [x] zmień reducer w `combineReducers` na `countries` łatwiej będzie dostać się w ten sposób do danych

**Comment by mraq1234** [comment]
- [ ] _czy faktycznie potrzebujemy akcji getCountries ?_

Nie potrzebujemy bo mapujemy `state` do `props` a początkowa wartość `state` zawiera dane z pliku `countries.json`. Zastanawiam się tylko czy jak dodamy nowe państwo (w sensie jako funkcjonalność aplikacji) to nadal będzie działało ... ale chyba tak bo podczas dodawania państwa zmutujemy stan do wartości z nowo dodanym państwem ... chyba

**Comment by mraq1234** [comment]
W zadaniu do submod8.3 (branch master) chyba jednak potrzebujemy wywołać getCountries bo testujemy działanie zarodka aplikacji za pomocą `redux-devtools` i warto wywołać jakąś akcję która coś robi :))

**Comment by kacgrzes** [comment]
tak, stan `coutries` się zmieni, więc `getCountries` nie jest generalnie potrzene. Do pobierania danych ze stora reduxowego dobrą praktyką jest używanie tzw. selektorów
